Repository 42Box/iOS, pull requests merged in 2024-05, with the labels that each got.

#269 fix: default url logic
  HowToUse.md
  Project.swift
  README.md
  iBox/Sources/CustomLaunchScreen/CustomLaunchScreenViewController.swift
  iBox/Sources/Extension/UIView+Extension.swift
  iBox/Sources/Initializer/DefaultData.swift
  iBox/Sources/Initializer/DefaultDataModel.swift
  iBox/Sources/Shared/WebViewPreloader.swift
Labels: 🐞 Bug, 📄 Documentation

#273 docs: Update README.md
  README.md
Labels: 📄 Documentation

#276 fix: defaultFolders url이 없는 경우 폴더를 생성하지 않음.
  iBox/Sources/Initializer/DefaultData.swift
  iBox/Sources/Initializer/DefaultDataModel.swift
  iBox/Sources/Settings/Reset/ResetViewController.swift
Labels: 🐞 Bug

#277 Main Version 1.0.2 🦊
  Project.swift
  iBox/Sources/Initializer/DefaultData.swift
  iBox/Sources/Initializer/DefaultDataModel.swift
  iBox/Sources/Settings/Reset/ResetViewController.swift
Labels: 🐞 Bug

#279 fix: change GuideView url
  Project.swift
  iBox/Sources/Initializer/DefaultDataModel.swift
  iBox/Sources/Settings/Guide/GuideViewController.swift
Labels: 🐞 Bug

#282 fix: 아이패드 대응 UIActivityViewController popover 설정
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/BoxListViewController.swift
Labels: 🐞 Bug

#284 feat: 북마크 추가 시 폴더 없을 때 색상 추가
  iBox/Sources/AddBookmark/AddBookmarkView.swift
  iBox/Sources/AddBookmark/AddBookmarkViewController.swift
Labels: ✨ Enhancement

#287 docs: Edit app download url in README.md
  README.md
Labels: 📄 Documentation
