Repository 42Box/iOS, pull requests merged in 2024-04, with the labels that each got.

#135 fix: move folder error
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/BoxListViewModel.swift
Labels: 🐞 Bug

#137 feat: add bookmark and folder in main view
  iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
  iBox/Sources/BoxList/AddBookmark/AddBookmarkViewController.swift
  iBox/Sources/BoxList/AddBookmark/FolderListView.swift
  iBox/Sources/BoxList/AddBookmark/FolderListViewController.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/BoxList/BoxListViewModel.swift
  iBox/Sources/Shared/UserDefaultsManager.swift
Labels: ✨ Enhancement

#146 feat: Back Swipe Gesture 추가
  iBox/Sources/Base/BaseViewController.swift
Labels: ✨ Enhancement

#141 feat: context menu preview
  iBox/Sources/BoxList/BoxListView.swift
Labels: ✨ Enhancement

#145 feat: share extension 시 name 전달
  ShareExtension/ShareViewController.swift
  iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
  iBox/Sources/BoxList/AddBookmark/AddBookmarkViewController.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/BoxList/BoxListViewModel.swift
  iBox/Sources/CustomLaunchScreen/CustomLaunchScreenViewController.swift
  iBox/Sources/SceneDelegate.swift
  iBox/Sources/Shared/GlobalURLManager.swift
  iBox/Sources/Shared/URLDataManager.swift
  iBox/Sources/Shared/URLdecoder.swift
Labels: ✨ Enhancement

#148 fix : 병합 충돌 해결
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/BoxList/BoxListViewModel.swift
Labels: 🐞 Bug

#157 feat: set responder in AddBookmarkView/#156
  iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
Labels: ✨ Enhancement

#168 feat: 진동 추가
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/Main/MainTabBarController.swift
  iBox/Sources/Model/SettingsItem.swift
  iBox/Sources/Settings/SettingsView.swift
  iBox/Sources/Settings/SettingsViewModel.swift
  iBox/Sources/Shared/UserDefaultsManager.swift
Labels: ✨ Enhancement

#172 style: Share Extension UI 변경
  ShareExtension/ShareViewController.swift
  ShareExtension/View/ShareExtensionBackGroundView.swift
Labels: 💄 UI/UX

#165 feat: Add clearButton in nameTextView
  iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
Labels: ✨ Enhancement

#170 feat: 웹뷰 내 로딩 추적
  iBox/Sources/Web/WebView.swift
Labels: ✨ Enhancement

#174 fix: Command ValidateEmbeddedBinary failed 문제 해결
  Project.swift
Labels: 🐞 Bug

#163 feat: textView 키보드 타입 변경
  iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
Labels: ✨ Enhancement

#166 feat: add custom refresh control
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/Extension/UIColor+Extension.swift
  iBox/Sources/Extension/UIFont+Extension.swift
  iBox/Sources/Web/RefreshControl.swift
  iBox/Sources/Web/WebView.swift
  iBox/Sources/Web/WebViewController.swift
Labels: ✨ Enhancement

#178 feat: back gesture in favorite view
  iBox/Sources/Shared/WebViewPreloader.swift
Labels: ✨ Enhancement

#184 refactor: FavoriteView WebView로 변경
  iBox/Sources/Extension/Notification+Extension.swift
  iBox/Sources/Favorite/FavoriteView.swift
  iBox/Sources/Settings/Reset/ResetViewController.swift
  iBox/Sources/Shared/WebViewPreloader.swift
Labels: ✨ Enhancement

#186 feat: 새 창으로 열기 옵션 링크 내부에서 열기
  iBox/Sources/Web/WebView.swift
Labels: ✨ Enhancement

#189 refactor: FolderListCell 내 checkmark 변경
  iBox/Sources/BoxList/AddBookmark/FolderListCell.swift
Labels: ⚒ Refactor

#192 fix: ShareExtension의 로직+Context 변경 /#182
  Project.swift
  ShareExtension/Resources/Media.xcassets/128.imageset/128 1.png
  ShareExtension/Resources/Media.xcassets/128.imageset/128.png
  ShareExtension/Resources/Media.xcassets/128.imageset/Contents.json
  ShareExtension/Resources/Media.xcassets/Contents.json
  ShareExtension/ShareViewController.swift
  ShareExtension/Sources/Extension/ShareExtension+UIColor+Extension.swift
  ShareExtension/Sources/Extension/ShareExtension+UIbutton+Extension.swift
  ShareExtension/Sources/ShareViewController.swift
  ShareExtension/Sources/View/ShareExtensionBackGroundView.swift
  ShareExtension/View/ShareExtensionBackGroundView.swift
  iBox/Sources/AddBookmark/AddBookmarkView.swift
  iBox/Sources/AddBookmark/AddBookmarkViewController.swift
  iBox/Sources/AddBookmark/FolderListCell.swift
  iBox/Sources/AddBookmark/FolderListView.swift
  iBox/Sources/AddBookmark/FolderListViewController.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/CustomLaunchScreen/CustomLaunchScreenViewController.swift
  iBox/Sources/Extension/UIViewController+Extension.swift
  iBox/Sources/Model/Metadata.swift
  iBox/Sources/SceneDelegate.swift
  iBox/Sources/Shared/AddBookmarkManager.swift
  iBox/Sources/Shared/URLDataManager.swift
  iBox/Sources/Shared/URLdecoder.swift
  iBox/Sources/Web/WebViewController.swift
Labels: ✨ Enhancement

#196 fix: SettingItemCell chevron 버튼 터치 안 되는 문제 해결
  iBox/Sources/Settings/SettingsItemCell.swift
Labels: 🐞 Bug

#198 feat: 폴더 버튼 꾹 누를 때 진동 추가
  iBox/Sources/BoxList/BoxListView.swift
Labels: ✨ Enhancement

#201 style: 앱의 전반적인 폰트 수정
  iBox/Sources/AddBookmark/AddBookmarkViewController.swift
  iBox/Sources/AddBookmark/FolderListView.swift
  iBox/Sources/AddBookmark/FolderListViewController.swift
  iBox/Sources/BoxList/BoxListCell.swift
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/FolderView.swift
  iBox/Sources/Extension/UIFont+Extension.swift
  iBox/Sources/Settings/Reset/ResetView.swift
Labels: ✨ Enhancement

#203 fix: bookmark move error
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/BoxListViewModel.swift
Labels: 🐞 Bug

#204 Dev/194 feat folder open시 해당 폴더로 스크롤/#194
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/BoxListViewModel.swift
  iBox/Sources/Favorite/FavoriteView.swift
Labels: ✨ Enhancement

#206 fix: url encoding decoding 관련 수정
  ShareExtension/Sources/ShareViewController.swift
  iBox/Sources/Shared/AddBookmarkManager.swift
  iBox/Sources/Web/WebViewController.swift
Labels: 🐞 Bug

#208 feat: context edit bookmark
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/Shared/WebCacheManager.swift
Labels: ✨ Enhancement

#212 fix: 폴더 비었을 때 모드에 따른 여우 색 변경
  iBox/Sources/BoxList/BoxListView.swift
Labels: 🐞 Bug

#216 feat: 사용자가 입력한 URL에 https://가 없을 경우 자동으로 추가하는 기능 구현
  iBox/Sources/AddBookmark/AddBookmarkViewController.swift
Labels: ✨ Enhancement

#226 feat: loading 중 skeletonview
  Project.swift
  Tuist/Dependencies.swift
  iBox/Sources/AddBookmark/AddBookmarkView.swift
  iBox/Sources/AddBookmark/AddBookmarkViewController.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/Extension/UIViewController+Extension.swift
  iBox/Sources/Model/BookmarkError.swift
  iBox/Sources/Shared/AddBookmarkManager.swift
Labels: ✨ Enhancement

#224 feat: addbookmarkview logic in favorite view/#222
  ShareExtension/Sources/View/ShareExtensionBackGroundView.swift
  iBox/Sources/Extension/UIView+Extension.swift
  iBox/Sources/Extension/UIViewController+Extension.swift
  iBox/Sources/Favorite/FavoriteViewController.swift
  iBox/Sources/Web/WebViewController.swift
Labels: ✨ Enhancement

#227 feat: webview error page/#225
  iBox/Sources/Error/ErrorPageView.swift
  iBox/Sources/Error/ErrorPageViewController.swift
  iBox/Sources/Web/WebView.swift
  iBox/Sources/Web/WebViewController.swift
Labels: ✨ Enhancement

#221 feat: 소소한 수정
  Project.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/Model/SettingsItem.swift
  iBox/Sources/Settings/Guide/GuideView.swift
  iBox/Sources/Settings/Guide/GuideViewController.swift
  iBox/Sources/Settings/HomeTab/HomeTabSelectorViewController.swift
  iBox/Sources/Settings/SettingsViewController.swift
  iBox/Sources/Settings/SettingsViewModel.swift
  iBox/Sources/Web/WebView.swift
Labels: ✨ Enhancement

#233 fix: http url 처리
  iBox/Sources/Shared/AddBookmarkManager.swift
Labels: 🐞 Bug

#235 feat: remove preload
  iBox/Sources/AppDelegate.swift
  iBox/Sources/Favorite/FavoriteView.swift
  iBox/Sources/Favorite/FavoriteViewController.swift
  iBox/Sources/Model/SettingsItem.swift
  iBox/Sources/Settings/SettingsView.swift
  iBox/Sources/Settings/SettingsViewModel.swift
  iBox/Sources/Shared/UserDefaultsManager.swift
Labels: ✨ Enhancement

#237 fix: 북마크 추가 시 url 안에 있는 # 그대로 처리
  iBox/Sources/AddBookmark/AddBookmarkViewController.swift
Labels: 🐞 Bug

#230 fix: 외부 application extension item 처리/#229
  Project.swift
  ShareExtension/Sources/ShareViewController.swift
Labels: 🐞 Bug

#239 feat: 앱 소개 리드미 연결
  iBox/Sources/Settings/Guide/GuideViewController.swift
Labels: ✨ Enhancement

#241 feat: error view/#231
  iBox/Sources/AppDelegate.swift
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/CustomLaunchScreen/CustomLaunchScreenView.swift
  iBox/Sources/CustomLaunchScreen/CustomLaunchScreenViewController.swift
  iBox/Sources/Error/ErrorCode.swift
  iBox/Sources/Error/ErrorPageView.swift
  iBox/Sources/Error/ErrorPageViewController.swift
  iBox/Sources/Extension/UIButton+Extension.swift
  iBox/Sources/Extension/UIColor+Extension.swift
  iBox/Sources/Extension/UIView+Extension.swift
  iBox/Sources/Settings/Reset/ResetSuccessView.swift
  iBox/Sources/Shared/Animator/FullSizePresentationController.swift
  iBox/Sources/Shared/Animator/SlideInPresentationAnimator.swift
  iBox/Sources/Shared/AppStateManager.swift
  iBox/Sources/Shared/SlideInPresentationManager.swift
  iBox/Sources/Web/WebViewController.swift
Labels: ✨ Enhancement

#245 fix: ShareExtension modalview backgroundcolor 수정
  Project.swift
  ShareExtension/Sources/ShareViewController.swift
  ShareExtension/Sources/View/ShareExtensionPanelView.swift
Labels: ⚒ Refactor

#248 style: ErrorPageView 레이아웃 수정
  iBox/Sources/Error/ErrorPageView.swift
Labels: ✨ Enhancement

#249 fix: 아이패드 대응 UIAlertConteollr preferredStyle 수정
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/BoxList/EditFolder/EditFolderViewController.swift
Labels: 🐞 Bug

#253 fix: web view 안에서 새 창 이동 안되는 경우 처리
  .gitignore
  iBox/Sources/Web/WebView.swift
Labels: 🐞 Bug

#251 feat: built CI/CD pipeline
  .github/workflows/Deployment.yml
  .gitignore
  Gemfile
  Makefile
  ShareExtension/Sources/ShareViewController.swift
  Tuist/Signing/debug.cer.encrypted
  Tuist/Signing/debug.p12.encrypted
  Tuist/Signing/iBox.Debug.mobileprovision
  Tuist/Signing/iBox.Release.mobileprovision
  Tuist/Signing/iBoxShareExtension.Debug.mobileprovision
  Tuist/Signing/iBoxShareExtension.Release.mobileprovision
  Tuist/Signing/release.cer.encrypted
  Tuist/Signing/release.p12.encrypted
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
  fastlane/report.xml
  iBox/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  iBox/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  iBox/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  iBox/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  iBox/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  iBox/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  iBox/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  iBox/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  iBox/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  iBox/Resources/Assets.xcassets/AppIcons/Contents.json
  iBox/Resources/Assets.xcassets/AppIcons/playstore.imageset/playstore.png
  iBox/Resources/Assets.xcassets/appstore.imageset/Contents.json
  iBox/Resources/Assets.xcassets/appstore.imageset/appstore.png
  iBox/Resources/Assets.xcassets/playstore.imageset/Contents.json
  iBox/Resources/Assets.xcassets/playstore.imageset/playstore.png
Labels: ✨ Enhancement
