Repository 42Box/iOS, pull requests merged in 2024-03, with the labels that each got.

#90 feat: WebView에 progressBar 추가
  iBox/Sources/Web/WebView.swift
Labels: ✨ Enhancement

#94 feat: refreshcontrol 추가
  iBox/ShareExtension/ShareViewController.swift
  iBox/ShareExtension/View/ShareExtensionBackGroundView.swift
  iBox/Sources/Favorite/FavoriteView.swift
  iBox/Sources/Web/WebView.swift
Labels: ✨ Enhancement

#96 feat: edit folders
  iBox/Sources/Base/BaseViewController.swift
  iBox/Sources/BoxList/BoxListSectionViewModel.swift
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/BoxList/BoxListViewModel.swift
  iBox/Sources/BoxList/Edit/EditView.swift
  iBox/Sources/BoxList/EditFolder/EditFolderCell.swift
  iBox/Sources/BoxList/EditFolder/EditFolderView.swift
  iBox/Sources/BoxList/EditFolder/EditFolderViewController.swift
  iBox/Sources/BoxList/EditFolder/EditFolderViewModel.swift
  iBox/Sources/BoxList/FolderButton.swift
  iBox/Sources/BoxList/FolderView.swift
  iBox/Sources/Extension/UIColor+Extension.swift
  iBox/Sources/Model/Folder.swift
  iBox/Sources/Shared/CoreDataManager.swift
Labels: ✨ Enhancement

#95 feat: BoxList 테이블뷰에 Swipe Action 추가
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/BoxList/BoxListViewModel.swift
Labels: ✨ Enhancement

#105 fix: change directory share extension
  ShareExtension/ShareViewController.swift
  ShareExtension/View/ShareExtensionBackGroundView.swift
  iBox/iBox.entitlements
Labels: 🏛 Structure

#107 feat: 설정 화면 수정
  iBox/Resources/Assets.xcassets/42pack_icon/42flip/42flip/42flip_01.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/42flip/42flip/42flip_010.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/42flip/42flip/42flip_011.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/42flip/42flip/42flip_02.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/42flip/42flip/42flip_03.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/42flip/42flip/42flip_04.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/42flip/42flip/42flip_05.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/42flip/42flip/42flip_06.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/42flip/42flip/42flip_07.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/42flip/42flip/42flip_08.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/42flip/42flip/42flip_09.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/cat/cat_page0.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/cat/cat_page1.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/cat/cat_page2.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/cat/cat_page3.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/cat/cat_page4.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/fox/fox_page0.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/fox/fox_page1.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/fox/fox_page2.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/fox/fox_page3.imageset/Contents.json
  iBox/Resources/Assets.xcassets/42pack_icon/fox/fox_page4.imageset/Contents.json
  iBox/Sources/Main/MainTabBarController.swift
  iBox/Sources/Model/SettingsItem.swift
  iBox/Sources/MyPage/MyPageCellViewModel.swift
  iBox/Sources/MyPage/MyPageSectionViewModel.swift
  iBox/Sources/MyPage/Profile/ProfileView.swift
  iBox/Sources/MyPage/Profile/ProfileViewController.swift
  iBox/Sources/Settings/HomeTab/HomeTabSelectorCell.swift
  iBox/Sources/Settings/HomeTab/HomeTabSelectorView.swift
  iBox/Sources/Settings/HomeTab/HomeTabSelectorViewController.swift
  iBox/Sources/Settings/HomeTab/HomeTabSelectorViewModel.swift
  iBox/Sources/Settings/Reset/ResetView.swift
  iBox/Sources/Settings/Reset/ResetViewController.swift
  iBox/Sources/Settings/SettingsCellViewModel.swift
  iBox/Sources/Settings/SettingsItemCell.swift
  iBox/Sources/Settings/SettingsSectionViewModel.swift
  iBox/Sources/Settings/SettingsView.swift
  iBox/Sources/Settings/SettingsViewController.swift
  iBox/Sources/Settings/SettingsViewModel.swift
  iBox/Sources/Settings/Theme/ThemeCell.swift
  iBox/Sources/Settings/Theme/ThemeView.swift
  iBox/Sources/Settings/Theme/ThemeViewController.swift
  iBox/Sources/Settings/Theme/ThemeViewModel.swift
Labels: ✨ Enhancement

#115 feat: WebView에서 http 연결 허용
  Project.swift
Labels: ✨ Enhancement

#108 feat: 북마크 편집 기능(삭제, 이동, 수정)
  iBox/Sources/Base/BaseViewController.swift
  iBox/Sources/BoxList/BoxListCell.swift
  iBox/Sources/BoxList/BoxListCellViewModel.swift
  iBox/Sources/BoxList/BoxListSectionViewModel.swift
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/BoxList/BoxListViewModel.swift
  iBox/Sources/BoxList/EditBookmark/EditBookmarkView.swift
  iBox/Sources/BoxList/EditBookmark/EditBookmarkViewController.swift
  iBox/Sources/BoxList/EditFolder/EditFolderViewModel.swift
  iBox/Sources/Model/Bookmark.swift
  iBox/Sources/Model/Folder.swift
  iBox/Sources/Shared/CoreDataManager.swift
  iBox/Sources/Web/WebViewController.swift
Labels: ✨ Enhancement

#110 feat: 북마크 추가화면 구성
  iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
  iBox/Sources/BoxList/AddBookmark/AddBookmarkViewController.swift
  iBox/Sources/BoxList/AddBookmark/FolderListCell.swift
  iBox/Sources/BoxList/AddBookmark/FolderListView.swift
  iBox/Sources/BoxList/AddBookmark/FolderListViewController.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/SceneDelegate.swift
  iBox/Sources/Shared/GlobalURLManager.swift
Labels: ✨ Enhancement

#117 feat: 방문했던 url 상태 기억
  iBox/Sources/BoxList/BoxListView.swift
  iBox/Sources/BoxList/BoxListViewController.swift
  iBox/Sources/Shared/WebCacheManager.swift
Labels: ✨ Enhancement

#120 feat: FolderListView 추가기능 구현
  iBox/Sources/BoxList/AddBookmark/AddBookmarkViewController.swift
  iBox/Sources/BoxList/AddBookmark/FolderListCell.swift
  iBox/Sources/BoxList/AddBookmark/FolderListView.swift
  iBox/Sources/BoxList/AddBookmark/FolderListViewController.swift
  iBox/Sources/Model/Folder.swift
  iBox/Sources/Shared/UserDefaultsManager.swift
Labels: ✨ Enhancement

#122 fix: WebView ProgressView 안 보이는 문제
  iBox/Sources/Web/WebView.swift
Labels: 🐞 Bug
